### ISSUE TITLE
[nRF5X Bluetooth Low Energy] Doesn't work on iPhone

### ISSUE THREAD

**Issue by niklasad1** [helena-project/tock#659] opened 2017-10-17 18:15 UTC
Hi,

As noticed in [#649](https://github.com/helena-project/tock/pull/649) the Bluetooth Low Energy advertisements can't be found on iPhone using the app  ```nRF Connect``` and need to be fixed!

Currently, it works on Android (at least on Samsung S6).
It need to be investigated further!!

**Comment by niklasad1** [comment] 2017-11-29 09:40
Well, since I updated iOS it seems to work fine anyone who can verify?

**Comment by alevy** [comment] 2017-11-29 16:06
It would be useful to figure out if this is a bug in iOS, in our advertising driver implementation, or in the particular advertising packet the test app sends. E.g. seeing if an advertisement generated from the nRF-SDK shows up.

I don't have an iOS device so I can't help and it sounds like at @niklasad1's now upgraded device won't help us anymore either (since it works now) :).

I'm inclined to close this for now. Thoughts?

**Comment by bradjc** [comment] 2017-11-29 18:03
We can always re-open it if anyone can reproduce it.

**Comment by ppannuto** [comment] 2017-11-29 18:04
I can test this afternoon when I get in and close if it’s fixed here too

**Comment by ppannuto** [comment] 2017-11-29 21:47
Can confirm that this still an issue and the advertisement does not appear on iOS 11.1.2 with nrfConnect or LightBlue. Branden found it on his phone, but the MAC address is listed as `ANONYMOUS`, which we've never seen before:

![image](https://user-images.githubusercontent.com/339422/33400609-853a1f98-d50b-11e7-9ca0-f225e2639178.png)

**Comment by alevy** [comment] 2017-11-29 22:23
@ppannuto this has not generally been an issue you for you all with  the NRFs, right? I.e. you have a bunch of applications that use the NRF51 with the Nordic softdevice---I think you've never had this kind of issue?

**Comment by niklasad1** [comment] 2017-11-29 22:30
Thanks, false positive I must have tested this on my other branch sorry :cry: 
Been a while since I been on the real ```master branch``` looks pretty weird on Android too my. 
The app is currently using address [0, 0, 0, 0, 0, 0] which may be the problem since it is not valid BLE address.

However, this works smooth on my other branch so this issue will remain open until that one is merged!

**Comment by ppannuto** [comment] 2017-11-29 22:32
I don't recall it being an issue before, but I also haven't tested nrf BLE much in a while, a bunch has changed. I suspect the invalid BLE address is the issue - iOS is presumably just dropping it.

**Comment by brghena** [comment] 2017-11-29 22:38
OH. Yeah, having all zeros as the address probably makes it not show up on iOS. I'd believe that easily.

**Closed** 2017-12-02 17:53 UTC
Labels: bug
