### ISSUE TITLE
make debug failure on Mac

### ISSUE THREAD

**Issue by nealjack** [helena-project/tock#635] opened 2017-10-03 18:24 UTC
The default installed `sed` on Mac is incompatible with `gnu-sed`. Attempting to make debug results in the following error:

```
sed: 1: "s/(FLASH.*ORIGIN[ =]*)( ...": \1 not defined in the RE
make: *** [build/cortex-m0/cortex-m0.userland_debug.ld] Error 1
```

I fixed this by replacing the default `sed` with `gnu-sed` using the following brew command:

```
brew install gnu-sed --with-default-names
```

Either this should be documented in the getting started guide, or the make system should be fixed to accommodate Mac's non-gnu `sed`. I think fixing is a better solution than replacing.

**Comment by ppannuto** [comment] 2017-10-03 19:51
Sigh.. duplicate of #616. I can try to puzzle this out later today.

**Closed by ppannuto** 2017-10-03 19:51 UTC
